import { Inter } from 'next/font/google'
import './globals.css'
import Headers from '@/layouts/Headers'
import Footer from '@/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  )
}
